In [1]:
# Reading csv file from colab uploaded files to pandas Data Frame
import pandas as pd
dataset_old=pd.read_csv('/content/census_2011 - census_2011.csv.csv')
dataset_old

,District code,State name,District name,Population,Male,Female,Literate,Male_Literate,Female_Literate,SC,...,Power_Parity_Rs_90000_150000,Power_Parity_Rs_45000_150000,Power_Parity_Rs_150000_240000,Power_Parity_Rs_240000_330000,Power_Parity_Rs_150000_330000,Power_Parity_Rs_330000_425000,Power_Parity_Rs_425000_545000,Power_Parity_Rs_330000_545000,Power_Parity_Above_Rs_545000,Total_Power_Parity
0,1,JAMMU AND KASHMIR,Kupwara,870354.0,474190.0,396164.0,439654.0,282823.0,156831.0,1048.0,...,94.0,588.0,71.0,101.0,172.0,74.0,10.0,84.0,15.0,1119.0
1,2,JAMMU AND KASHMIR,Badgam,753745.0,NaN,355704.0,335649.0,207741.0,127908.0,NaN,...,126.0,562.0,72.0,89.0,161.0,96.0,28.0,124.0,18.0,1066.0
2,3,JAMMU AND KASHMIR,Leh(Ladakh),133487.0,78971.0,54516.0,93770.0,62834.0,30936.0,488.0,...,46.0,122.0,15.0,22.0,NaN,20.0,NaN,NaN,17.0,242.0
3,4,JAMMU AND KASHMIR,Kargil,140802.0,NaN,63017.0,NaN,56301.0,29935.0,18.0,...,27.0,114.0,12.0,18.0,30.0,19.0,3.0,22.0,7.0,214.0
4,5,JAMMU AND KASHMIR,Punch,NaN,251899.0,224936.0,261724.0,163333.0,98391.0,556.0,...,78.0,346.0,35.0,50.0,85.0,59.0,8.0,67.0,12.0,629.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
635,636,PONDICHERRY,Mahe,41816.0,19143.0,22673.0,36470.0,16610.0,19860.0,144.0,...,2316.0,4309.0,1370.0,838.0,2208.0,576.0,978.0,1554.0,1446.0,10027.0
636,637,PONDICHERRY,Karaikal,200222.0,97809.0,102413.0,154916.0,79903.0,75013.0,35348.0,...,1063.0,2408.0,665.0,340.0,1005.0,246.0,NaN,729.0,341.0,4890.0
637,638,ANDAMAN AND NICOBAR ISLANDS,Nicobars,36842.0,20727.0,NaN,25332.0,15397.0,9935.0,0.0,...,685.0,1895.0,212.0,134.0,346.0,70.0,120.0,190.0,84.0,3151.0
638,639,ANDAMAN AND NICOBAR ISLANDS,North AND Middle Andaman,105597.0,54861.0,50736.0,78683.0,43186.0,35497.0,0.0,...,685.0,1895.0,212.0,NaN,346.0,70.0,120.0,190.0,84.0,3151.0
639,640,ANDAMAN AND NICOBAR ISLANDS,South Andaman,NaN,127283.0,110859.0,190266.0,105794.0,84472.0,0.0,...,1371.0,3020.0,649.0,368.0,1017.0,265.0,497.0,762.0,376.0,5782.0

In [2]:
# Renaming some column names for uniformity
dataset=dataset_old.rename(columns={'State name':'State/UT','District name':'District','Male_Literate':'Literate_Male','Female_Literate':'Literate_Female','Rural_Households':'Households_Rural','Urban_Households':'Households_Urban','Age_Group_0_29':'Young_and_Adult','Age_Group_30_49':'Middle_Aged','Age_Group_50':'Senior_Citizen','Age not stated':'Age_Not_Stated','District code':'District_Code','Young and_Adult':'Young_and_Adult'})

In [3]:
# Replacing the first character of State/UT to upper case and the rest to lower case, using 'title' for uniformity
dataset['State/UT']=dataset['State/UT'].apply(str.title)

In [4]:
# Replacing the names for uniformity
dataset=dataset.replace(to_replace=['Andaman And Nicobar Islands','Jammu And Kashmir','Nct Of Delhi','Daman And Diu','Dadra And Nagar Haveli'],value=['Andaman and Nicobar Islands','Jammu and Kashmir','Nct of Delhi','Daman and Diu','Dadra and Nagar Haveli'])

In [5]:
# State name for some Districts, are changed to Telangana after state division from Andhra Pradesh
District_Telangana=['Adilabad','Nizamabad','Karimnagar','Medak','Hyderabad','Rangareddy','Mahbubnagar','Nalgonda','Warangal','Khammam']

dataset.loc[dataset['District'].isin(District_Telangana),'State/UT']='Telangana'

In [6]:
# State name for some Districts, are changed to Ladakh after state division from Jammu and Kashmir
District_Ladakh=['Leh(Ladakh)','Kargil']

dataset.loc[dataset['District'].isin(District_Ladakh),'State/UT']='Ladakh'

In [7]:
# Filling missing values in the dataset by aggregation
dataset['Male'].fillna(value=dataset['Population']-dataset['Female'],inplace=True)
dataset['Female'].fillna(value=dataset['Population']-dataset['Male'],inplace=True)
dataset['Population'].fillna(value=dataset['Male']+dataset['Female'],inplace=True)

<ipython-input-7-dd7e7feea51b>:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  dataset['Male'].fillna(value=dataset['Population']-dataset['Female'],inplace=True)
<ipython-input-7-dd7e7feea51b>:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  dataset['Female'].fillna(value=dataset['Population']-dataset['Male'],inplace=True)
<ipython-input-7-dd7e7feea51b>:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  dataset['Population'].fillna(value=dataset['Male']+dataset['Female'],inplace=True)

In [8]:
# Filling missing values in the dataset by aggregation
dataset['Literate'].fillna(dataset['Literate_Male']+dataset['Literate_Female'],inplace=True)
dataset['Literate_Male'].fillna(dataset['Literate']-dataset['Literate_Female'],inplace=True)
dataset['Literate_Female'].fillna(dataset['Literate']-dataset['Literate_Male'],inplace=True)

<ipython-input-8-183ce946d438>:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  dataset['Literate'].fillna(dataset['Literate_Male']+dataset['Literate_Female'],inplace=True)
<ipython-input-8-183ce946d438>:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  dataset['Literate_Male'].fillna(dataset['Literate']-dataset['Literate_Female'],inplace=True)
<ipython-input-8-183ce946d438>:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  dataset['Literate_Female'].fillna(dataset['Literate']-dataset['Literate_Male'],inplace=True)

In [9]:
# Filling missing values in the dataset by aggregation
dataset['Households'].fillna(dataset['Households_Rural']+dataset['Households_Urban'],inplace=True)
dataset['Households_Rural'].fillna(dataset['Households']-dataset['Households_Urban'],inplace=True)
dataset['Households_Urban'].fillna(dataset['Households']-dataset['Households_Rural'],inplace=True)

<ipython-input-9-1013633dabe0>:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  dataset['Households'].fillna(dataset['Households_Rural']+dataset['Households_Urban'],inplace=True)
<ipython-input-9-1013633dabe0>:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  dataset['Households_Rural'].fillna(dataset['Households']-dataset['Households_Urban'],inplace=True)
<ipython-input-9-1013633dabe0>:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  dataset['Households_Urban'].fillna(dataset['Households']-dataset['Households_Rural'],inplace=True)

In [10]:
# Filling missing values in the dataset by aggregation
dataset['ST'].fillna(dataset['Male_ST']+dataset['Female_ST'],inplace=True)
dataset['Male_ST'].fillna(dataset['ST']-dataset['Female_ST'],inplace=True)
dataset['Female_ST'].fillna(dataset['ST']-dataset['Male_ST'],inplace=True)

<ipython-input-10-b73d73ef86a9>:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  dataset['ST'].fillna(dataset['Male_ST']+dataset['Female_ST'],inplace=True)
<ipython-input-10-b73d73ef86a9>:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  dataset['Male_ST'].fillna(dataset['ST']-dataset['Female_ST'],inplace=True)
<ipython-input-10-b73d73ef86a9>:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  dataset['Female_ST'].fillna(dataset['ST']-dataset['Male_ST'],inplace=True)

In [11]:
# Filling missing values in the dataset by aggregation
dataset['SC'].fillna(dataset['Male_SC']+dataset['Female_SC'],inplace=True)
dataset['Male_SC'].fillna(dataset['SC']-dataset['Female_SC'],inplace=True)
dataset['Female_SC'].fillna(dataset['SC']-dataset['Male_SC'],inplace=True)

<ipython-input-11-9549abaaca60>:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  dataset['SC'].fillna(dataset['Male_SC']+dataset['Female_SC'],inplace=True)
<ipython-input-11-9549abaaca60>:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  dataset['Male_SC'].fillna(dataset['SC']-dataset['Female_SC'],inplace=True)
<ipython-input-11-9549abaaca60>:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  dataset['Female_SC'].fillna(dataset['SC']-dataset['Male_SC'],inplace=True)

In [12]:
# Filling missing values in the dataset by aggregation
dataset['Workers'].fillna(dataset['Male_Workers']+dataset['Female_Workers'],inplace=True)
dataset['Male_Workers'].fillna(dataset['Workers']-dataset['Female_Workers'],inplace=True)
dataset['Female_Workers'].fillna(dataset['Workers']-dataset['Female_Workers'],inplace=True)

<ipython-input-12-fd65a77656d1>:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  dataset['Workers'].fillna(dataset['Male_Workers']+dataset['Female_Workers'],inplace=True)
<ipython-input-12-fd65a77656d1>:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  dataset['Male_Workers'].fillna(dataset['Workers']-dataset['Female_Workers'],inplace=True)
<ipython-input-12-fd65a77656d1>:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  dataset['Female_Workers'].fillna(dataset['Workers']-dataset['Female_Workers'],inplace=True)

In [13]:
# Filling missing values in the dataset by aggregation
dataset['Workers'].fillna(dataset['Marginal_Workers']+dataset['Main_Workers'],inplace=True)
dataset['Marginal_Workers'].fillna(dataset['Workers']-dataset['Main_Workers'],inplace=True)
dataset['Main_Workers'].fillna(dataset['Workers']-dataset['Marginal_Workers'],inplace=True)

<ipython-input-13-7db7688c2e34>:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  dataset['Workers'].fillna(dataset['Marginal_Workers']+dataset['Main_Workers'],inplace=True)
<ipython-input-13-7db7688c2e34>:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  dataset['Marginal_Workers'].fillna(dataset['Workers']-dataset['Main_Workers'],inplace=True)
<ipython-input-13-7db7688c2e34>:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  dataset['Main_Workers'].fillna(dataset['Workers']-dataset['Marginal_Workers'],inplace=True)

In [14]:
# Filling missing values in the dataset by aggregation
dataset['Workers'].fillna(dataset['Cultivator_Workers']+dataset['Agricultural_Workers']+dataset['Household_Workers']+dataset['Other_Workers'],inplace=True)
dataset['Cultivator_Workers'].fillna(dataset['Workers']-dataset['Agricultural_Workers']-dataset['Household_Workers']-dataset['Other_Workers'],inplace=True)
dataset['Agricultural_Workers'].fillna(dataset['Workers']-dataset['Cultivator_Workers']-dataset['Household_Workers']-dataset['Other_Workers'],inplace=True)
dataset['Household_Workers'].fillna(dataset['Workers']-dataset['Cultivator_Workers']-dataset['Agricultural_Workers']-dataset['Other_Workers'],inplace=True)
dataset['Other_Workers'].fillna(dataset['Workers']-dataset['Cultivator_Workers']-dataset['Agricultural_Workers']-dataset['Household_Workers'],inplace=True)

<ipython-input-14-955c3bbf8297>:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  dataset['Workers'].fillna(dataset['Cultivator_Workers']+dataset['Agricultural_Workers']+dataset['Household_Workers']+dataset['Other_Workers'],inplace=True)
<ipython-input-14-955c3bbf8297>:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  dataset['Cultivator_Workers'].fillna(dataset['Workers']-dataset['Agricultural_Workers']-dataset['Household_Workers']-dataset['Other_Workers'],inplace=True)
<ipython-input-14-955c3bbf8297>:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  dataset['Agricultural_Workers'].fillna(dataset['Workers']-dataset['Cultivator_Workers']-dataset['Household_Workers']-dataset['Other_Workers'],inplace=True)
<ipython-input-14-955c3bbf8297>:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  dataset['Household_Workers'].fillna(dataset['Workers']-dataset['Cultivator_Workers']-dataset['Agricultural_Workers']-dataset['Other_Workers'],inplace=True)
<ipython-input-14-955c3bbf8297>:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  dataset['Other_Workers'].fillna(dataset['Workers']-dataset['Cultivator_Workers']-dataset['Agricultural_Workers']-dataset['Household_Workers'],inplace=True)

In [15]:
# Filling missing values in the dataset by aggregation
dataset['Population'].fillna(dataset['Workers']+dataset['Non_Workers'],inplace=True)
dataset['Workers'].fillna(dataset['Population']-dataset['Non_Workers'],inplace=True)
dataset['Non_Workers'].fillna(dataset['Population']+dataset['Workers'],inplace=True)

<ipython-input-15-11efbadbb7f5>:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  dataset['Population'].fillna(dataset['Workers']+dataset['Non_Workers'],inplace=True)
<ipython-input-15-11efbadbb7f5>:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  dataset['Workers'].fillna(dataset['Population']-dataset['Non_Workers'],inplace=True)
<ipython-input-15-11efbadbb7f5>:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  dataset['Non_Workers'].fillna(dataset['Population']+dataset['Workers'],inplace=True)

In [16]:
# Filling missing values in the dataset by aggregation
dataset['Population'].fillna(dataset['Hindus']+dataset['Muslims']+dataset['Christians']+dataset['Sikhs']+dataset['Buddhists']+dataset['Jains']+dataset['Others_Religions']+dataset['Religion_Not_Stated'],inplace=True)
dataset['Hindus'].fillna(dataset['Population']-dataset['Muslims']-dataset['Christians']-dataset['Sikhs']-dataset['Buddhists']-dataset['Jains']-dataset['Others_Religions']-dataset['Religion_Not_Stated'],inplace=True)
dataset['Muslims'].fillna(dataset['Population']-dataset['Hindus']-dataset['Christians']-dataset['Sikhs']-dataset['Buddhists']-dataset['Jains']-dataset['Others_Religions']-dataset['Religion_Not_Stated'],inplace=True)
dataset['Christians'].fillna(dataset['Population']-dataset['Muslims']-dataset['Hindus']-dataset['Sikhs']-dataset['Buddhists']-dataset['Jains']-dataset['Others_Religions']-dataset['Religion_Not_Stated'],inplace=True)
dataset['Sikhs'].fillna(dataset['Population']-dataset['Muslims']-dataset['Christians']-dataset['Hindus']-dataset['Buddhists']-dataset['Jains']-dataset['Others_Religions']-dataset['Religion_Not_Stated'],inplace=True)
dataset['Buddhists'].fillna(dataset['Population']-dataset['Muslims']-dataset['Christians']+dataset['Sikhs']-dataset['Hindus']-dataset['Jains']-dataset['Others_Religions']-dataset['Religion_Not_Stated'],inplace=True)
dataset['Jains'].fillna(dataset['Population']-dataset['Muslims']-dataset['Christians']-dataset['Sikhs']-dataset['Buddhists']-dataset['Hindus']-dataset['Others_Religions']-dataset['Religion_Not_Stated'],inplace=True)
dataset['Others_Religions'].fillna(dataset['Population']-dataset['Muslims']-dataset['Christians']-dataset['Sikhs']-dataset['Buddhists']-dataset['Jains']-dataset['Hindus']-dataset['Religion_Not_Stated'],inplace=True)
dataset['Religion_Not_Stated'].fillna(dataset['Population']-dataset['Muslims']-dataset['Christians']-dataset['Sikhs']-dataset['Buddhists']-dataset['Jains']-dataset['Others_Religions']-dataset['Hindus'],inplace=True)

<ipython-input-16-c72d71068f82>:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  dataset['Population'].fillna(dataset['Hindus']+dataset['Muslims']+dataset['Christians']+dataset['Sikhs']+dataset['Buddhists']+dataset['Jains']+dataset['Others_Religions']+dataset['Religion_Not_Stated'],inplace=True)
<ipython-input-16-c72d71068f82>:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  dataset['Hindus'].fillna(dataset['Population']-dataset['Muslims']-dataset['Christians']-dataset['Sikhs']-dataset['Buddhists']-dataset['Jains']-dataset['Others_Religions']-dataset['Religion_Not_Stated'],inplace=True)
<ipython-input-16-c72d71068f82>:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  dataset['Muslims'].fillna(dataset['Population']-dataset['Hindus']-dataset['Christians']-dataset['Sikhs']-dataset['Buddhists']-dataset['Jains']-dataset['Others_Religions']-dataset['Religion_Not_Stated'],inplace=True)
<ipython-input-16-c72d71068f82>:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  dataset['Christians'].fillna(dataset['Population']-dataset['Muslims']-dataset['Hindus']-dataset['Sikhs']-dataset['Buddhists']-dataset['Jains']-dataset['Others_Religions']-dataset['Religion_Not_Stated'],inplace=True)
<ipython-input-16-c72d71068f82>:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  dataset['Sikhs'].fillna(dataset['Population']-dataset['Muslims']-dataset['Christians']-dataset['Hindus']-dataset['Buddhists']-dataset['Jains']-dataset['Others_Religions']-dataset['Religion_Not_Stated'],inplace=True)
<ipython-input-16-c72d71068f82>:7: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  dataset['Buddhists'].fillna(dataset['Population']-dataset['Muslims']-dataset['Christians']+dataset['Sikhs']-dataset['Hindus']-dataset['Jains']-dataset['Others_Religions']-dataset['Religion_Not_Stated'],inplace=True)
<ipython-input-16-c72d71068f82>:8: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  dataset['Jains'].fillna(dataset['Population']-dataset['Muslims']-dataset['Christians']-dataset['Sikhs']-dataset['Buddhists']-dataset['Hindus']-dataset['Others_Religions']-dataset['Religion_Not_Stated'],inplace=True)
<ipython-input-16-c72d71068f82>:9: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  dataset['Others_Religions'].fillna(dataset['Population']-dataset['Muslims']-dataset['Christians']-dataset['Sikhs']-dataset['Buddhists']-dataset['Jains']-dataset['Hindus']-dataset['Religion_Not_Stated'],inplace=True)
<ipython-input-16-c72d71068f82>:10: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  dataset['Religion_Not_Stated'].fillna(dataset['Population']-dataset['Muslims']-dataset['Christians']-dataset['Sikhs']-dataset['Buddhists']-dataset['Jains']-dataset['Others_Religions']-dataset['Hindus'],inplace=True)

In [17]:
# Filling missing values in the dataset by aggregation
dataset['Total_Education'].fillna(dataset['Literate_Education']+dataset['Illiterate_Education'],inplace=True)
dataset['Literate_Education'].fillna(dataset['Total_Education']-dataset['Illiterate_Education'],inplace=True)
dataset['Illiterate_Education'].fillna(dataset['Total_Education']-dataset['Literate_Education'],inplace=True)

<ipython-input-17-070df22604f8>:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  dataset['Total_Education'].fillna(dataset['Literate_Education']+dataset['Illiterate_Education'],inplace=True)
<ipython-input-17-070df22604f8>:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  dataset['Literate_Education'].fillna(dataset['Total_Education']-dataset['Illiterate_Education'],inplace=True)
<ipython-input-17-070df22604f8>:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  dataset['Illiterate_Education'].fillna(dataset['Total_Education']-dataset['Literate_Education'],inplace=True)

In [18]:
# Filling missing values in the dataset by aggregation
dataset['Population'].fillna(dataset['Young_and_Adult']+dataset['Middle_Aged']+dataset['Senior_Citizen']+dataset['Age_Not_Stated'],inplace=True)
dataset['Young_and_Adult'].fillna(dataset['Population']-dataset['Middle_Aged']-dataset['Senior_Citizen']-dataset['Age_Not_Stated'],inplace=True)
dataset['Middle_Aged'].fillna(dataset['Population']-dataset['Young_and_Adult']-dataset['Senior_Citizen']-dataset['Age_Not_Stated'],inplace=True)
dataset['Senior_Citizen'].fillna(dataset['Population']-dataset['Young_and_Adult']-dataset['Middle_Aged']-dataset['Age_Not_Stated'],inplace=True)
dataset['Age_Not_Stated'].fillna(dataset['Population']-dataset['Young_and_Adult']-dataset['Middle_Aged']-dataset['Senior_Citizen'],inplace=True)

<ipython-input-18-96e2844549d0>:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  dataset['Population'].fillna(dataset['Young_and_Adult']+dataset['Middle_Aged']+dataset['Senior_Citizen']+dataset['Age_Not_Stated'],inplace=True)
<ipython-input-18-96e2844549d0>:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  dataset['Young_and_Adult'].fillna(dataset['Population']-dataset['Middle_Aged']-dataset['Senior_Citizen']-dataset['Age_Not_Stated'],inplace=True)
<ipython-input-18-96e2844549d0>:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  dataset['Middle_Aged'].fillna(dataset['Population']-dataset['Young_and_Adult']-dataset['Senior_Citizen']-dataset['Age_Not_Stated'],inplace=True)
<ipython-input-18-96e2844549d0>:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  dataset['Senior_Citizen'].fillna(dataset['Population']-dataset['Young_and_Adult']-dataset['Middle_Aged']-dataset['Age_Not_Stated'],inplace=True)
<ipython-input-18-96e2844549d0>:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  dataset['Age_Not_Stated'].fillna(dataset['Population']-dataset['Young_and_Adult']-dataset['Middle_Aged']-dataset['Senior_Citizen'],inplace=True)

In [19]:
# Filling missing values in the dataset by aggregation
dataset['Literate_Education'].fillna(dataset['Below_Primary_Education']+dataset['Primary_Education']+dataset['Middle_Education']+dataset['Secondary_Education']+dataset['Higher_Education']+dataset['Graduate_Education']+dataset['Other_Education'],inplace=True)
dataset['Below_Primary_Education'].fillna(dataset['Literate_Education']-dataset['Primary_Education']-dataset['Middle_Education']-dataset['Secondary_Education']-dataset['Higher_Education']-dataset['Graduate_Education']-dataset['Other_Education'],inplace=True)
dataset['Primary_Education'].fillna(dataset['Literate_Education']-dataset['Below_Primary_Education']-dataset['Middle_Education']-dataset['Secondary_Education']-dataset['Higher_Education']-dataset['Graduate_Education']-dataset['Other_Education'],inplace=True)
dataset['Middle_Education'].fillna(dataset['Literate_Education']-dataset['Below_Primary_Education']-dataset['Primary_Education']-dataset['Secondary_Education']-dataset['Higher_Education']-dataset['Graduate_Education']-dataset['Other_Education'],inplace=True)
dataset['Secondary_Education'].fillna(dataset['Literate_Education']-dataset['Below_Primary_Education']-dataset['Primary_Education']-dataset['Middle_Education']-dataset['Higher_Education']-dataset['Graduate_Education']-dataset['Other_Education'],inplace=True)
dataset['Higher_Education'].fillna(dataset['Literate_Education']-dataset['Below_Primary_Education']-dataset['Primary_Education']-dataset['Middle_Education']-dataset['Secondary_Education']-dataset['Graduate_Education']-dataset['Other_Education'],inplace=True)
dataset['Graduate_Education'].fillna(dataset['Literate_Education']-dataset['Below_Primary_Education']-dataset['Primary_Education']-dataset['Middle_Education']-dataset['Secondary_Education']-dataset['Higher_Education']-dataset['Other_Education'],inplace=True)
dataset['Other_Education'].fillna(dataset['Literate_Education']-dataset['Below_Primary_Education']-dataset['Primary_Education']-dataset['Middle_Education']-dataset['Secondary_Education']-dataset['Higher_Education']-dataset['Graduate_Education'],inplace=True)

<ipython-input-19-21dddff41d7d>:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  dataset['Literate_Education'].fillna(dataset['Below_Primary_Education']+dataset['Primary_Education']+dataset['Middle_Education']+dataset['Secondary_Education']+dataset['Higher_Education']+dataset['Graduate_Education']+dataset['Other_Education'],inplace=True)
<ipython-input-19-21dddff41d7d>:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  dataset['Below_Primary_Education'].fillna(dataset['Literate_Education']-dataset['Primary_Education']-dataset['Middle_Education']-dataset['Secondary_Education']-dataset['Higher_Education']-dataset['Graduate_Education']-dataset['Other_Education'],inplace=True)
<ipython-input-19-21dddff41d7d>:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  dataset['Primary_Education'].fillna(dataset['Literate_Education']-dataset['Below_Primary_Education']-dataset['Middle_Education']-dataset['Secondary_Education']-dataset['Higher_Education']-dataset['Graduate_Education']-dataset['Other_Education'],inplace=True)
<ipython-input-19-21dddff41d7d>:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  dataset['Middle_Education'].fillna(dataset['Literate_Education']-dataset['Below_Primary_Education']-dataset['Primary_Education']-dataset['Secondary_Education']-dataset['Higher_Education']-dataset['Graduate_Education']-dataset['Other_Education'],inplace=True)
<ipython-input-19-21dddff41d7d>:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  dataset['Secondary_Education'].fillna(dataset['Literate_Education']-dataset['Below_Primary_Education']-dataset['Primary_Education']-dataset['Middle_Education']-dataset['Higher_Education']-dataset['Graduate_Education']-dataset['Other_Education'],inplace=True)
<ipython-input-19-21dddff41d7d>:7: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  dataset['Higher_Education'].fillna(dataset['Literate_Education']-dataset['Below_Primary_Education']-dataset['Primary_Education']-dataset['Middle_Education']-dataset['Secondary_Education']-dataset['Graduate_Education']-dataset['Other_Education'],inplace=True)
<ipython-input-19-21dddff41d7d>:8: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  dataset['Graduate_Education'].fillna(dataset['Literate_Education']-dataset['Below_Primary_Education']-dataset['Primary_Education']-dataset['Middle_Education']-dataset['Secondary_Education']-dataset['Higher_Education']-dataset['Other_Education'],inplace=True)
<ipython-input-19-21dddff41d7d>:9: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  dataset['Other_Education'].fillna(dataset['Literate_Education']-dataset['Below_Primary_Education']-dataset['Primary_Education']-dataset['Middle_Education']-dataset['Secondary_Education']-dataset['Higher_Education']-dataset['Graduate_Education'],inplace=True)

In [20]:
# filling missing values in the datasaet by aggregation
dataset['Main_source_of_drinking_water_Other_sources_Spring_River_Canal_Tank_Pond_Lake_Other_sources__Households'].fillna(dataset['Main_source_of_drinking_water_Spring_Households']+dataset['Main_source_of_drinking_water_River_Canal_Households']+dataset['Main_source_of_drinking_water_Other_sources_Households']+dataset['Main_source_of_drinking_water_Tank_Pond_Lake_Households'],inplace=True)
dataset['Main_source_of_drinking_water_Spring_Households'].fillna(dataset['Main_source_of_drinking_water_Other_sources_Spring_River_Canal_Tank_Pond_Lake_Other_sources__Households']-dataset['Main_source_of_drinking_water_River_Canal_Households']-dataset['Main_source_of_drinking_water_Other_sources_Households']-dataset['Main_source_of_drinking_water_Tank_Pond_Lake_Households'],inplace=True)
dataset['Main_source_of_drinking_water_River_Canal_Households'].fillna(dataset['Main_source_of_drinking_water_Other_sources_Spring_River_Canal_Tank_Pond_Lake_Other_sources__Households']-dataset['Main_source_of_drinking_water_Spring_Households']-dataset['Main_source_of_drinking_water_Other_sources_Households']-dataset['Main_source_of_drinking_water_Tank_Pond_Lake_Households'],inplace=True)
dataset['Main_source_of_drinking_water_Other_sources_Households'].fillna(dataset['Main_source_of_drinking_water_Other_sources_Spring_River_Canal_Tank_Pond_Lake_Other_sources__Households']-dataset['Main_source_of_drinking_water_Spring_Households']-dataset['Main_source_of_drinking_water_River_Canal_Households']-dataset['Main_source_of_drinking_water_Tank_Pond_Lake_Households'],inplace=True)
dataset['Main_source_of_drinking_water_Tank_Pond_Lake_Households'].fillna(dataset['Main_source_of_drinking_water_Other_sources_Spring_River_Canal_Tank_Pond_Lake_Other_sources__Households']-dataset['Main_source_of_drinking_water_Spring_Households']-dataset['Main_source_of_drinking_water_River_Canal_Households']-dataset['Main_source_of_drinking_water_Other_sources_Households'],inplace=True)

<ipython-input-20-1432d8c2622d>:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  dataset['Main_source_of_drinking_water_Other_sources_Spring_River_Canal_Tank_Pond_Lake_Other_sources__Households'].fillna(dataset['Main_source_of_drinking_water_Spring_Households']+dataset['Main_source_of_drinking_water_River_Canal_Households']+dataset['Main_source_of_drinking_water_Other_sources_Households']+dataset['Main_source_of_drinking_water_Tank_Pond_Lake_Households'],inplace=True)
<ipython-input-20-1432d8c2622d>:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  dataset['Main_source_of_drinking_water_Spring_Households'].fillna(dataset['Main_source_of_drinking_water_Other_sources_Spring_River_Canal_Tank_Pond_Lake_Other_sources__Households']-dataset['Main_source_of_drinking_water_River_Canal_Households']-dataset['Main_source_of_drinking_water_Other_sources_Households']-dataset['Main_source_of_drinking_water_Tank_Pond_Lake_Households'],inplace=True)
<ipython-input-20-1432d8c2622d>:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  dataset['Main_source_of_drinking_water_River_Canal_Households'].fillna(dataset['Main_source_of_drinking_water_Other_sources_Spring_River_Canal_Tank_Pond_Lake_Other_sources__Households']-dataset['Main_source_of_drinking_water_Spring_Households']-dataset['Main_source_of_drinking_water_Other_sources_Households']-dataset['Main_source_of_drinking_water_Tank_Pond_Lake_Households'],inplace=True)
<ipython-input-20-1432d8c2622d>:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  dataset['Main_source_of_drinking_water_Other_sources_Households'].fillna(dataset['Main_source_of_drinking_water_Other_sources_Spring_River_Canal_Tank_Pond_Lake_Other_sources__Households']-dataset['Main_source_of_drinking_water_Spring_Households']-dataset['Main_source_of_drinking_water_River_Canal_Households']-dataset['Main_source_of_drinking_water_Tank_Pond_Lake_Households'],inplace=True)
<ipython-input-20-1432d8c2622d>:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  dataset['Main_source_of_drinking_water_Tank_Pond_Lake_Households'].fillna(dataset['Main_source_of_drinking_water_Other_sources_Spring_River_Canal_Tank_Pond_Lake_Other_sources__Households']-dataset['Main_source_of_drinking_water_Spring_Households']-dataset['Main_source_of_drinking_water_River_Canal_Households']-dataset['Main_source_of_drinking_water_Other_sources_Households'],inplace=True)

In [21]:
# filling missing values in the datasaet by aggregation
dataset['Household_size_1_to_2_persons'].fillna(dataset['Household_size_1_person_Households']+dataset['Household_size_2_persons_Households'],inplace=True)
dataset['Household_size_1_person_Households'].fillna(dataset['Household_size_1_to_2_persons']-dataset['Household_size_2_persons_Households'],inplace=True)
dataset['Household_size_2_persons_Households'].fillna(dataset['Household_size_1_to_2_persons']-dataset['Household_size_1_person_Households'],inplace=True)

<ipython-input-21-3149914021dd>:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  dataset['Household_size_1_to_2_persons'].fillna(dataset['Household_size_1_person_Households']+dataset['Household_size_2_persons_Households'],inplace=True)
<ipython-input-21-3149914021dd>:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  dataset['Household_size_1_person_Households'].fillna(dataset['Household_size_1_to_2_persons']-dataset['Household_size_2_persons_Households'],inplace=True)
<ipython-input-21-3149914021dd>:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  dataset['Household_size_2_persons_Households'].fillna(dataset['Household_size_1_to_2_persons']-dataset['Household_size_1_person_Households'],inplace=True)

In [22]:
# filling missing values in the datasaet by aggregation
dataset['Household_size_3_to_5_persons_Households'].fillna(dataset['Household_size_3_persons_Households']+dataset['Household_size_4_persons_Households']+dataset['Household_size_5_persons_Households'],inplace=True)
dataset['Household_size_3_persons_Households'].fillna(dataset['Household_size_3_to_5_persons_Households']-dataset['Household_size_4_persons_Households']-dataset['Household_size_5_persons_Households'],inplace=True)
dataset['Household_size_4_persons_Households'].fillna(dataset['Household_size_3_to_5_persons_Households']-dataset['Household_size_3_persons_Households']-dataset['Household_size_5_persons_Households'],inplace=True)
dataset['Household_size_5_persons_Households'].fillna(dataset['Household_size_3_to_5_persons_Households']-dataset['Household_size_3_persons_Households']-dataset['Household_size_4_persons_Households'],inplace=True)

<ipython-input-22-477bb53e79a7>:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  dataset['Household_size_3_to_5_persons_Households'].fillna(dataset['Household_size_3_persons_Households']+dataset['Household_size_4_persons_Households']+dataset['Household_size_5_persons_Households'],inplace=True)
<ipython-input-22-477bb53e79a7>:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  dataset['Household_size_3_persons_Households'].fillna(dataset['Household_size_3_to_5_persons_Households']-dataset['Household_size_4_persons_Households']-dataset['Household_size_5_persons_Households'],inplace=True)
<ipython-input-22-477bb53e79a7>:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  dataset['Household_size_4_persons_Households'].fillna(dataset['Household_size_3_to_5_persons_Households']-dataset['Household_size_3_persons_Households']-dataset['Household_size_5_persons_Households'],inplace=True)
<ipython-input-22-477bb53e79a7>:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  dataset['Household_size_5_persons_Households'].fillna(dataset['Household_size_3_to_5_persons_Households']-dataset['Household_size_3_persons_Households']-dataset['Household_size_4_persons_Households'],inplace=True)

In [23]:
# filling missing values in the datasaet by aggregation
dataset['Married_couples_3_or_more_Households'].fillna(dataset['Married_couples_3_Households']+dataset['Married_couples_4_Households']+dataset['Married_couples_5__Households'],inplace=True)
dataset['Married_couples_3_Households'].fillna(dataset['Married_couples_3_or_more_Households']-dataset['Married_couples_4_Households']-dataset['Married_couples_5__Households'],inplace=True)
dataset['Married_couples_4_Households'].fillna(dataset['Married_couples_3_or_more_Households']-dataset['Married_couples_3_Households']-dataset['Married_couples_5__Households'],inplace=True)
dataset['Married_couples_5__Households'].fillna(dataset['Married_couples_3_or_more_Households']-dataset['Married_couples_3_Households']-dataset['Married_couples_4_Households'],inplace=True)

<ipython-input-23-dbf3b28d1d08>:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  dataset['Married_couples_3_or_more_Households'].fillna(dataset['Married_couples_3_Households']+dataset['Married_couples_4_Households']+dataset['Married_couples_5__Households'],inplace=True)
<ipython-input-23-dbf3b28d1d08>:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  dataset['Married_couples_3_Households'].fillna(dataset['Married_couples_3_or_more_Households']-dataset['Married_couples_4_Households']-dataset['Married_couples_5__Households'],inplace=True)
<ipython-input-23-dbf3b28d1d08>:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  dataset['Married_couples_4_Households'].fillna(dataset['Married_couples_3_or_more_Households']-dataset['Married_couples_3_Households']-dataset['Married_couples_5__Households'],inplace=True)
<ipython-input-23-dbf3b28d1d08>:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  dataset['Married_couples_5__Households'].fillna(dataset['Married_couples_3_or_more_Households']-dataset['Married_couples_3_Households']-dataset['Married_couples_4_Households'],inplace=True)

In [24]:
# filling missing values in the datasaet by aggregation
dataset['Power_Parity_Rs_45000_150000'].fillna(dataset['Power_Parity_Rs_45000_90000']+dataset['Power_Parity_Rs_90000_150000'],inplace=True)
dataset['Power_Parity_Rs_45000_90000'].fillna(dataset['Power_Parity_Rs_45000_150000']-dataset['Power_Parity_Rs_90000_150000'],inplace=True)
dataset['Power_Parity_Rs_90000_150000'].fillna(dataset['Power_Parity_Rs_45000_150000']-dataset['Power_Parity_Rs_45000_90000'],inplace=True)

<ipython-input-24-749544afd0e4>:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  dataset['Power_Parity_Rs_45000_150000'].fillna(dataset['Power_Parity_Rs_45000_90000']+dataset['Power_Parity_Rs_90000_150000'],inplace=True)
<ipython-input-24-749544afd0e4>:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  dataset['Power_Parity_Rs_45000_90000'].fillna(dataset['Power_Parity_Rs_45000_150000']-dataset['Power_Parity_Rs_90000_150000'],inplace=True)
<ipython-input-24-749544afd0e4>:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  dataset['Power_Parity_Rs_90000_150000'].fillna(dataset['Power_Parity_Rs_45000_150000']-dataset['Power_Parity_Rs_45000_90000'],inplace=True)

In [25]:
# filling missing values in the datasaet by aggregation
dataset['Power_Parity_Rs_150000_330000'].fillna(dataset['Power_Parity_Rs_150000_240000']+dataset['Power_Parity_Rs_240000_330000'],inplace=True)
dataset['Power_Parity_Rs_150000_240000'].fillna(dataset['Power_Parity_Rs_150000_330000']-dataset['Power_Parity_Rs_240000_330000'],inplace=True)
dataset['Power_Parity_Rs_240000_330000'].fillna(dataset['Power_Parity_Rs_150000_330000']-dataset['Power_Parity_Rs_150000_240000'],inplace=True)

<ipython-input-25-cb828c346a62>:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  dataset['Power_Parity_Rs_150000_330000'].fillna(dataset['Power_Parity_Rs_150000_240000']+dataset['Power_Parity_Rs_240000_330000'],inplace=True)
<ipython-input-25-cb828c346a62>:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  dataset['Power_Parity_Rs_150000_240000'].fillna(dataset['Power_Parity_Rs_150000_330000']-dataset['Power_Parity_Rs_240000_330000'],inplace=True)
<ipython-input-25-cb828c346a62>:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  dataset['Power_Parity_Rs_240000_330000'].fillna(dataset['Power_Parity_Rs_150000_330000']-dataset['Power_Parity_Rs_150000_240000'],inplace=True)

In [26]:
# filling missing values in the datasaet by aggregation
dataset['Power_Parity_Rs_330000_545000'].fillna(dataset['Power_Parity_Rs_330000_425000']+dataset['Power_Parity_Rs_425000_545000'],inplace=True)
dataset['Power_Parity_Rs_330000_425000'].fillna(dataset['Power_Parity_Rs_330000_545000']-dataset['Power_Parity_Rs_425000_545000'],inplace=True)
dataset['Power_Parity_Rs_425000_545000'].fillna(dataset['Power_Parity_Rs_330000_545000']-dataset['Power_Parity_Rs_330000_425000'],inplace=True)

<ipython-input-26-df551c11f7ad>:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  dataset['Power_Parity_Rs_330000_545000'].fillna(dataset['Power_Parity_Rs_330000_425000']+dataset['Power_Parity_Rs_425000_545000'],inplace=True)
<ipython-input-26-df551c11f7ad>:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  dataset['Power_Parity_Rs_330000_425000'].fillna(dataset['Power_Parity_Rs_330000_545000']-dataset['Power_Parity_Rs_425000_545000'],inplace=True)
<ipython-input-26-df551c11f7ad>:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  dataset['Power_Parity_Rs_425000_545000'].fillna(dataset['Power_Parity_Rs_330000_545000']-dataset['Power_Parity_Rs_330000_425000'],inplace=True)

In [27]:
# filling missing values in the datasaet by aggregation
dataset['Total_Power_Parity'].fillna(dataset['Power_Parity_Less_than_Rs_45000']+dataset['Power_Parity_Rs_45000_150000']+dataset['Power_Parity_Rs_150000_330000']+dataset['Power_Parity_Rs_330000_545000']+dataset['Power_Parity_Above_Rs_545000'],inplace=True)
dataset['Power_Parity_Less_than_Rs_45000'].fillna(dataset['Total_Power_Parity']-dataset['Power_Parity_Rs_45000_150000']-dataset['Power_Parity_Rs_150000_330000']-dataset['Power_Parity_Rs_330000_545000']-dataset['Power_Parity_Above_Rs_545000'],inplace=True)
dataset['Power_Parity_Rs_45000_150000'].fillna(dataset['Total_Power_Parity']-dataset['Power_Parity_Less_than_Rs_45000']-dataset['Power_Parity_Rs_150000_330000']-dataset['Power_Parity_Rs_330000_545000']-dataset['Power_Parity_Above_Rs_545000'],inplace=True)
dataset['Power_Parity_Rs_150000_330000'].fillna(dataset['Total_Power_Parity']-dataset['Power_Parity_Less_than_Rs_45000']-dataset['Power_Parity_Rs_45000_150000']-dataset['Power_Parity_Rs_330000_545000']-dataset['Power_Parity_Above_Rs_545000'],inplace=True)
dataset['Power_Parity_Rs_330000_545000'].fillna(dataset['Total_Power_Parity']-dataset['Power_Parity_Less_than_Rs_45000']-dataset['Power_Parity_Rs_45000_150000']-dataset['Power_Parity_Rs_150000_330000']-dataset['Power_Parity_Above_Rs_545000'],inplace=True)
dataset['Power_Parity_Above_Rs_545000'].fillna(dataset['Total_Power_Parity']-dataset['Power_Parity_Less_than_Rs_45000']-dataset['Power_Parity_Rs_45000_150000']-dataset['Power_Parity_Rs_150000_330000']-dataset['Power_Parity_Rs_330000_545000'],inplace=True)

<ipython-input-27-756440ae75da>:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  dataset['Total_Power_Parity'].fillna(dataset['Power_Parity_Less_than_Rs_45000']+dataset['Power_Parity_Rs_45000_150000']+dataset['Power_Parity_Rs_150000_330000']+dataset['Power_Parity_Rs_330000_545000']+dataset['Power_Parity_Above_Rs_545000'],inplace=True)
<ipython-input-27-756440ae75da>:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  dataset['Power_Parity_Less_than_Rs_45000'].fillna(dataset['Total_Power_Parity']-dataset['Power_Parity_Rs_45000_150000']-dataset['Power_Parity_Rs_150000_330000']-dataset['Power_Parity_Rs_330000_545000']-dataset['Power_Parity_Above_Rs_545000'],inplace=True)
<ipython-input-27-756440ae75da>:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  dataset['Power_Parity_Rs_45000_150000'].fillna(dataset['Total_Power_Parity']-dataset['Power_Parity_Less_than_Rs_45000']-dataset['Power_Parity_Rs_150000_330000']-dataset['Power_Parity_Rs_330000_545000']-dataset['Power_Parity_Above_Rs_545000'],inplace=True)
<ipython-input-27-756440ae75da>:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  dataset['Power_Parity_Rs_150000_330000'].fillna(dataset['Total_Power_Parity']-dataset['Power_Parity_Less_than_Rs_45000']-dataset['Power_Parity_Rs_45000_150000']-dataset['Power_Parity_Rs_330000_545000']-dataset['Power_Parity_Above_Rs_545000'],inplace=True)
<ipython-input-27-756440ae75da>:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  dataset['Power_Parity_Rs_330000_545000'].fillna(dataset['Total_Power_Parity']-dataset['Power_Parity_Less_than_Rs_45000']-dataset['Power_Parity_Rs_45000_150000']-dataset['Power_Parity_Rs_150000_330000']-dataset['Power_Parity_Above_Rs_545000'],inplace=True)
<ipython-input-27-756440ae75da>:7: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  dataset['Power_Parity_Above_Rs_545000'].fillna(dataset['Total_Power_Parity']-dataset['Power_Parity_Less_than_Rs_45000']-dataset['Power_Parity_Rs_45000_150000']-dataset['Power_Parity_Rs_150000_330000']-dataset['Power_Parity_Rs_330000_545000'],inplace=True)

In [28]:
# count of missing values before cleaning

null_count=dataset_old.isnull().sum()

null_df=null_count.reset_index()
null_df.columns=['column','Missing values']

# count of missing values after cleaning

null_count1=dataset.isnull().sum()

null_df1=null_count1.reset_index()
null_df1.columns=['column','Missing values']

#finding the percentage of amount of missing data before data cleaning
null_df['percentage_missing_value before_cleaning']=(null_df['Missing values']/len(dataset_old))*100

#finding the percentage of amount of missing data after data cleaning
null_df['percentage_missing_value after_cleaning']=(null_df1['Missing values']/len(dataset))*100

null_df

,column,Missing values,percentage_missing_value before_cleaning,percentage_missing_value after_cleaning
0,District code,0,0.00000,0.00000
1,State name,0,0.00000,0.00000
2,District name,0,0.00000,0.00000
3,Population,30,4.68750,0.00000
4,Male,30,4.68750,0.15625
...,...,...,...,...
113,Power_Parity_Rs_330000_425000,33,5.15625,0.46875
114,Power_Parity_Rs_425000_545000,30,4.68750,0.46875
115,Power_Parity_Rs_330000_545000,23,3.59375,0.15625
116,Power_Parity_Above_Rs_545000,30,4.68750,0.62500
117,Total_Power_Parity,32,5.00000,0.93750

In [29]:
# pymongo installation
!python -m pip install "pymongo[srv]"

Collecting pymongo[srv]
  Downloading pymongo-4.10.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (22 kB)
WARNING: pymongo 4.10.1 does not provide the extra 'srv'
Collecting dnspython<3.0.0,>=1.16.0 (from pymongo[srv])
  Downloading dnspython-2.7.0-py3-none-any.whl.metadata (5.8 kB)
Downloading dnspython-2.7.0-py3-none-any.whl (313 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 313.6/313.6 kB 6.9 MB/s eta 0:00:00
Downloading pymongo-4.10.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.4/1.4 MB 33.4 MB/s eta 0:00:00
Installing collected packages: dnspython, pymongo
Successfully installed dnspython-2.7.0 pymongo-4.10.1

In [30]:
# Importing pymongo and json
import pymongo
import json

In [31]:
# Establishing connection between python and mongodb
from pymongo.mongo_client import MongoClient
from pymongo.server_api import ServerApi

uri = "mongodb+srv://kranthipenmetsa1:Kranthi!1@cluster0.zpdud.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"

# Create a new client and connect to the server
client = MongoClient(uri, server_api=ServerApi('1'))

# Send a ping to confirm a successful connection
try:
    client.admin.command('ping')
    print("Pinged your deployment. You successfully connected to MongoDB!")
except Exception as e:
    print(e)

Pinged your deployment. You successfully connected to MongoDB!

In [32]:
# Data in the dataset is changed into key value pair(records) and stored in variable x
#x=dataset.to_dict(orient='records')
#print(x)

In [33]:
# A database called 'Census_DB' is created in mongodb
db=client['Census_DB']

In [34]:
# A collection called 'Census' is created in 'Census_DB' and records are inserted using insert_many
#db.Census.insert_many(x)

In [35]:
# find function is colled from mongodb using cursor
cursor=db.Census.find()

In [36]:
# Using list to retrive the data vertically through cursor
list=[]
for i in cursor:
  list.append(i)

In [37]:
list

[{'_id': ObjectId('66eae254a553d550d3dcebb6'),
  'District_Code': 10,
  'State/UT': 'Jammu and Kashmir',
  'District': 'Srinagar',
  'Population': 1236829.0,
  'Male': 651124.0,
  'Female': 585705.0,
  'Literate': 748584.0,
  'Literate_Male': 431746.0,
  'Literate_Female': 316838.0,
  'SC': 1068.0,
  'Male_SC': 995.0,
  'Female_SC': 73.0,
  'ST': 8935.0,
  'Male_ST': 5021.0,
  'Female_ST': 3914.0,
  'Workers': 407188.0,
  'Male_Workers': 333151.0,
  'Female_Workers': 74037.0,
  'Main_Workers': 330547.0,
  'Marginal_Workers': 76641.0,
  'Non_Workers': 829641.0,
  'Cultivator_Workers': 12228.0,
  'Agricultural_Workers': 10408.0,
  'Household_Workers': 20095.0,
  'Other_Workers': 364457.0,
  'Hindus': 42540.0,
  'Muslims': 1177342.0,
  'Christians': 2746.0,
  'Sikhs': 12187.0,
  'Buddhists': 285.0,
  'Jains': 74.0,
  'Others_Religions': 2.0,
  'Religion_Not_Stated': 1653.0,
  'LPG_or_PNG_Households': 138119.0,
  'Housholds_with_Electric_Lighting': 165403.0,
  'Households_with_Internet': 16413.0,
  'Households_with_Computer': 33831.0,
  'Households_Rural': 4518.0,
  'Households_Urban': 257721.0,
  'Households': 262239.0,
  'Below_Primary_Education': 88911.0,
  'Primary_Education': 173309.0,
  'Middle_Education': 178723.0,
  'Secondary_Education': 176409.0,
  'Higher_Education': 132727.0,
  'Graduate_Education': 121856.0,
  'Other_Education': 32114.0,
  'Literate_Education': 904049.0,
  'Illiterate_Education': 310225.0,
  'Total_Education': 1214274.0,
  'Young_and_Adult': 693238.0,
  'Middle_Aged': 351561.0,
  'Senior_Citizen': 190330.0,
  'Age_Not_Stated': 1700.0,
  'Households_with_Bicycle': 44501.0,
  'Households_with_Car_Jeep_Van': 34586.0,
  'Households_with_Radio_Transistor': 129337.0,
  'Households_with_Scooter_Motorcycle_Moped': 39804.0,
  'Households_with_Telephone_Mobile_Phone_Landline_only': 12717.0,
  'Households_with_Telephone_Mobile_Phone_Mobile_only': 120553.0,
  'Households_with_TV_Computer_Laptop_Telephone_mobile_phone_and_Scooter_Car': 22024.0,
  'Households_with_Television': 152945.0,
  'Households_with_Telephone_Mobile_Phone': 157875.0,
  'Households_with_Telephone_Mobile_Phone_Both': 24605.0,
  'Condition_of_occupied_census_houses_Dilapidated_Households': 3715.0,
  'Households_with_separate_kitchen_Cooking_inside_house': 164293.0,
  'Having_bathing_facility_Total_Households': 164263.0,
  'Having_latrine_facility_within_the_premises_Total_Households': 164002.0,
  'Ownership_Owned_Households': 160923.0,
  'Ownership_Rented_Households': 5135.0,
  'Type_of_bathing_facility_Enclosure_without_roof_Households': 2302.0,
  'Type_of_fuel_used_for_cooking_Any_other_Households': nan,
  'Type_of_latrine_facility_Pit_latrine_Households': 4430.0,
  'Type_of_latrine_facility_Other_latrine_Households': 39455.0,
  'Type_of_latrine_facility_Night_soil_disposed_into_open_drain_Households': 33799.0,
  'Type_of_latrine_facility_Flush_pour_flush_latrine_connected_to_other_system_Households': 8101.0,
  'Not_having_bathing_facility_within_the_premises_Total_Households': 3185.0,
  'Not_having_latrine_facility_within_the_premises_Alternative_source_Open_Households': 2448.0,
  'Main_source_of_drinking_water_Un_covered_well_Households': 38.0,
  'Main_source_of_drinking_water_Handpump_Tubewell_Borewell_Households': 1563.0,
  'Main_source_of_drinking_water_Spring_Households': 55.0,
  'Main_source_of_drinking_water_River_Canal_Households': 669.0,
  'Main_source_of_drinking_water_Other_sources_Households': 317.0,
  'Main_source_of_drinking_water_Other_sources_Spring_River_Canal_Tank_Pond_Lake_Other_sources__Households': 1105.0,
  'Location_of_drinking_water_source_Near_the_premises_Households': 7457.0,
  'Location_of_drinking_water_source_Within_the_premises_Households': 157176.0,
  'Main_source_of_drinking_water_Tank_Pond_Lake_Households': 64.0,
  'Main_source_of_drinking_water_Tapwater_Households': 164426.0,
  'Main_source_of_drinking_water_Tubewell_Borehole_Households': 692.0,
  'Household_size_1_person_Households': 2326.0,
  'Household_size_2_persons_Households': 6626.0,
  'Household_size_1_to_2_persons': 8952.0,
  'Household_size_3_persons_Households': 15425.0,
  'Household_size_3_to_5_persons_Households': 94928.0,
  'Household_size_4_persons_Households': 37998.0,
  'Household_size_5_persons_Households': 41505.0,
  'Household_size_6_8_persons_Households': 49622.0,
  'Household_size_9_persons_and_above_Households': 13946.0,
  'Location_of_drinking_water_source_Away_Households': 2815.0,
  'Married_couples_1_Households': 117581.0,
  'Married_couples_2_Households': 23234.0,
  'Married_couples_3_Households': 6314.0,
  'Married_couples_3_or_more_Households': 7640.0,
  'Married_couples_4_Households': 1075.0,
  'Married_couples_5__Households': 251.0,
  'Married_couples_None_Households': 18993.0,
  'Power_Parity_Less_than_Rs_45000': 251.0,
  'Power_Parity_Rs_45000_90000': 427.0,
  'Power_Parity_Rs_90000_150000': 668.0,
  'Power_Parity_Rs_45000_150000': 1095.0,
  'Power_Parity_Rs_150000_240000': 319.0,
  'Power_Parity_Rs_240000_330000': 380.0,
  'Power_Parity_Rs_150000_330000': 699.0,
  'Power_Parity_Rs_330000_425000': 240.0,
  'Power_Parity_Rs_425000_545000': 370.0,
  'Power_Parity_Rs_330000_545000': 610.0,
  'Power_Parity_Above_Rs_545000': 445.0,
  'Total_Power_Parity': 3099.0},
 {'_id': ObjectId('66eae254a553d550d3dcebd2'),
  'District_Code': 38,
  'State/UT': 'Punjab',
  'District': 'Hoshiarpur',
  'Population': 1586625.0,
  'Male': 809057.0,
  'Female': 777568.0,
  'Literate': 1199699.0,
  'Literate_Male': 637927.0,
  'Literate_Female': 561772.0,
  'SC': 557504.0,
  'Male_SC': 284322.0,
  'Female_SC': 273182.0,
  'ST': 0.0,
  'Male_ST': 0.0,
  'Female_ST': 0.0,
  'Workers': 499822.0,
  'Male_Workers': 412506.0,
  'Female_Workers': 87316.0,
  'Main_Workers': 411011.0,
  'Marginal_Workers': 88811.0,
  'Non_Workers': 2086447.0,
  'Cultivator_Workers': 89772.0,
  'Agricultural_Workers': 74362.0,
  'Household_Workers': 15990.0,
  'Other_Workers': 319698.0,
  'Hindus': 1000743.0,
  'Muslims': 23089.0,
  'Christians': 14968.0,
  'Sikhs': 538208.0,
  'Buddhists': 3476.0,
  'Jains': 2034.0,
  'Others_Religions': 531.0,
  'Religion_Not_Stated': 3576.0,
  'LPG_or_PNG_Households': 201675.0,
  'Housholds_with_Electric_Lighting': 319930.0,
  'Households_with_Internet': 13747.0,
  'Households_with_Computer': 34328.0,
  'Households_Rural': 422673.0,
  'Households_Urban': 128592.0,
  'Households': 551265.0,
  'Below_Primary_Education': 143871.0,
  'Primary_Education': 256127.0,
  'Middle_Education': 238975.0,
  'Secondary_Education': 301435.0,
  'Higher_Education': 176013.0,
  'Graduate_Education': 93618.0,
  'Other_Education': 17427.0,
  'Literate_Education': 1227466.0,
  'Illiterate_Education': 294723.0,
  'Total_Education': 1522189.0,
  'Young_and_Adult': 831741.0,
  'Middle_Aged': 422782.0,
  'Senior_Citizen': 330671.0,
  'Age_Not_Stated': 1431.0,
  'Households_with_Bicycle': 227316.0,
  'Households_with_Car_Jeep_Van': 33720.0,
  'Households_with_Radio_Transistor': 62295.0,
  'Households_with_Scooter_Motorcycle_Moped': 166862.0,
  'Households_with_Telephone_Mobile_Phone_Landline_only': 24372.0,
  'Households_with_Telephone_Mobile_Phone_Mobile_only': 194786.0,
  'Households_with_TV_Computer_Laptop_Telephone_mobile_phone_and_Scooter_Car': 27207.0,
  'Households_with_Television': 285904.0,
  'Households_with_Telephone_Mobile_Phone': 278411.0,
  'Households_with_Telephone_Mobile_Phone_Both': 59253.0,
  'Condition_of_occupied_census_houses_Dilapidated_Households': 20255.0,
  'Households_with_separate_kitchen_Cooking_inside_house': 310810.0,
  'Having_bathing_facility_Total_Households': 285730.0,
  'Having_latrine_facility_within_the_premises_Total_Households': 210621.0,
  'Ownership_Owned_Households': 303081.0,
  'Ownership_Rented_Households': 17651.0,
  'Type_of_bathing_facility_Enclosure_without_roof_Households': 70856.0,
  'Type_of_fuel_used_for_cooking_Any_other_Households': 118.0,
  'Type_of_latrine_facility_Pit_latrine_Households': 25818.0,
  'Type_of_latrine_facility_Other_latrine_Households': 1753.0,
  'Type_of_latrine_facility_Night_soil_disposed_into_open_drain_Households': 633.0,
  'Type_of_latrine_facility_Flush_pour_flush_latrine_connected_to_other_system_Households': 4006.0,
  'Not_having_bathing_facility_within_the_premises_Total_Households': 43964.0,
  'Not_having_latrine_facility_within_the_premises_Alternative_source_Open_Households': 116787.0,
  'Main_source_of_drinking_water_Un_covered_well_Households': 1721.0,
  'Main_source_of_drinking_water_Handpump_Tubewell_Borewell_Households': 145269.0,
  'Main_source_of_drinking_water_Spring_Households': 101.0,
  'Main_source_of_drinking_water_River_Canal_Households': 125.0,
  'Main_source_of_drinking_water_Other_sources_Households': 4106.0,
  'Main_source_of_drinking_water_Other_sources_Spring_River_Canal_Tank_Pond_Lake_Other_sources__Households': 4460.0,
  'Location_of_drinking_water_source_Near_the_premises_Households': 37705.0,
  'Location_of_drinking_water_source_Within_the_premises_Households': 278909.0,
  'Main_source_of_drinking_water_Tank_Pond_Lake_Households': 128.0,
  'Main_source_of_drinking_water_Tapwater_Households': 177302.0,
  'Main_source_of_drinking_water_Tubewell_Borehole_Households': 52828.0,
  'Household_size_1_person_Households': 12002.0,
  'Household_size_2_persons_Households': 26350.0,
  'Household_size_1_to_2_persons': 38352.0,
  'Household_size_3_persons_Households': 44638.0,
  'Household_size_3_to_5_persons_Households': 198627.0,
  'Household_size_4_persons_Households': 80977.0,
  'Household_size_5_persons_Households': 73012.0,
  'Household_size_6_8_persons_Households': nan,
  'Household_size_9_persons_and_above_Households': 14213.0,
  'Location_of_drinking_water_source_Away_Households': 13080.0,
  'Married_couples_1_Households': 217844.0,
  'Married_couples_2_Households': 52307.0,
  'Married_couples_3_Households': 9712.0,
  'Married_couples_3_or_more_Households': 11214.0,
  'Married_couples_4_Households': 1309.0,
  'Married_couples_5__Households': 193.0,
  'Married_couples_None_Households': 48329.0,
  'Power_Parity_Less_than_Rs_45000': 167.0,
  'Power_Parity_Rs_45000_90000': 653.0,
  'Power_Parity_Rs_90000_150000': 925.0,
  'Power_Parity_Rs_45000_150000': 1578.0,
  'Power_Parity_Rs_150000_240000': 586.0,
  'Power_Parity_Rs_240000_330000': 357.0,
  'Power_Parity_Rs_150000_330000': 943.0,
  'Power_Parity_Rs_330000_425000': 360.0,
  'Power_Parity_Rs_425000_545000': 529.0,
  'Power_Parity_Rs_330000_545000': 889.0,
  'Power_Parity_Above_Rs_545000': 730.0,
  'Total_Power_Parity': 4305.0},
 {'_id': ObjectId('66eae254a553d550d3dcebb8'),
  'District_Code': 12,
  'State/UT': 'Jammu and Kashmir',
  'District': 'Pulwama',
  'Population': 560440.0,
  'Male': 293064.0,
  'Female': 267376.0,
  'Literate': 293958.0,
  'Literate_Male': 178326.0,
  'Literate_Female': 115632.0,
  'SC': 402.0,
  'Male_SC': 397.0,
  'Female_SC': 5.0,
  'ST': 22607.0,
  'Male_ST': 11837.0,
  'Female_ST': 10770.0,
  'Workers': 188420.0,
  'Male_Workers': 138428.0,
  'Female_Workers': 49992.0,
  'Main_Workers': 98306.0,
  'Marginal_Workers': 90114.0,
  'Non_Workers': 372020.0,
  'Cultivator_Workers': 49746.0,
  'Agricultural_Workers': 34080.0,
  'Household_Workers': 10615.0,
  'Other_Workers': 93979.0,
  'Hindus': 13840.0,
  'Muslims': 535159.0,
  'Christians': 1109.0,
  'Sikhs': 9440.0,
  'Buddhists': 35.0,
  'Jains': 6.0,
  'Others_Religions': 18.0,
  'Religion_Not_Stated': 833.0,
  'LPG_or_PNG_Households': 16828.0,
  'Housholds_with_Electric_Lighting': 73629.0,
  'Households_with_Internet': 1537.0,
  'Households_with_Computer': 5293.0,
  'Households_Rural': 147520.0,
  'Households_Urban': 21703.0,
  'Households': 169223.0,
  'Below_Primary_Education': 36201.0,
  'Primary_Education': 54808.0,
  'Middle_Education': 73991.0,
  'Secondary_Education': 67368.0,
  'Higher_Education': 40931.0,
  'Graduate_Education': 31286.0,
  'Other_Education': 5897.0,
  'Literate_Education': 310482.0,
  'Illiterate_Education': 190369.0,
  'Total_Education': 500851.0,
  'Young_and_Adult': 342601.0,
  'Middle_Aged': nan,
  'Senior_Citizen': nan,
  'Age_Not_Stated': 696.0,
  'Households_with_Bicycle': 5479.0,
  'Households_with_Car_Jeep_Van': 6164.0,
  'Households_with_Radio_Transistor': 51973.0,
  'Households_with_Scooter_Motorcycle_Moped': 4551.0,
  'Households_with_Telephone_Mobile_Phone_Landline_only': 1770.0,
  'Households_with_Telephone_Mobile_Phone_Mobile_only': 57529.0,
  'Households_with_TV_Computer_Laptop_Telephone_mobile_phone_and_Scooter_Car': 1478.0,
  'Households_with_Television': 45967.0,
  'Households_with_Telephone_Mobile_Phone': 65162.0,
  'Households_with_Telephone_Mobile_Phone_Both': 5863.0,
  'Condition_of_occupied_census_houses_Dilapidated_Households': 3568.0,
  'Households_with_separate_kitchen_Cooking_inside_house': nan,
  'Having_bathing_facility_Total_Households': 61749.0,
  'Having_latrine_facility_within_the_premises_Total_Households': 53836.0,
  'Ownership_Owned_Households': 80452.0,
  'Ownership_Rented_Households': 459.0,
  'Type_of_bathing_facility_Enclosure_without_roof_Households': 3940.0,
  'Type_of_fuel_used_for_cooking_Any_other_Households': 680.0,
  'Type_of_latrine_facility_Pit_latrine_Households': 5829.0,
  'Type_of_latrine_facility_Other_latrine_Households': 11679.0,
  'Type_of_latrine_facility_Night_soil_disposed_into_open_drain_Households': 664.0,
  'Type_of_latrine_facility_Flush_pour_flush_latrine_connected_to_other_system_Households': 4826.0,
  'Not_having_bathing_facility_within_the_premises_Total_Households': 19492.0,
  'Not_having_latrine_facility_within_the_premises_Alternative_source_Open_Households': 25493.0,
  'Main_source_of_drinking_water_Un_covered_well_Households': 212.0,
  'Main_source_of_drinking_water_Handpump_Tubewell_Borewell_Households': 13347.0,
  'Main_source_of_drinking_water_Spring_Households': 660.0,
  'Main_source_of_drinking_water_River_Canal_Households': 8108.0,
  'Main_source_of_drinking_water_Other_sources_Households': 929.0,
  'Main_source_of_drinking_water_Other_sources_Spring_River_Canal_Tank_Pond_Lake_Other_sources__Households': 10127.0,
  'Location_of_drinking_water_source_Near_the_premises_Households': 19320.0,
  'Location_of_drinking_water_source_Within_the_premises_Households': 50893.0,
  'Main_source_of_drinking_water_Tank_Pond_Lake_Households': 430.0,
  'Main_source_of_drinking_water_Tapwater_Households': 56749.0,
  'Main_source_of_drinking_water_Tubewell_Borehole_Households': 3413.0,
  'Household_size_1_person_Households': 705.0,
  'Household_size_2_persons_Households': 2291.0,
  'Household_size_1_to_2_persons': 2996.0,
  'Household_size_3_persons_Households': 5461.0,
  'Household_size_3_to_5_persons_Households': 32942.0,
  'Household_size_4_persons_Households': 11863.0,
  'Household_size_5_persons_Households': 15618.0,
  'Household_size_6_8_persons_Households': 31436.0,
  'Household_size_9_persons_and_above_Households': 13867.0,
  'Location_of_drinking_water_source_Away_Households': 11028.0,
  'Married_couples_1_Households': 55081.0,
  'Married_couples_2_Households': 15020.0,
  'Married_couples_3_Households': 3099.0,
  'Married_couples_3_or_more_Households': 3612.0,
  'Married_couples_4_Households': 439.0,
  'Married_couples_5__Households': 74.0,
  'Married_couples_None_Households': 7528.0,
  'Power_Parity_Less_than_Rs_45000': 213.0,
  'Power_Parity_Rs_45000_90000': 430.0,
  'Power_Parity_Rs_90000_150000': 119.0,
  'Power_Parity_Rs_45000_150000': 549.0,
  'Power_Parity_Rs_150000_240000': 71.0,
  'Power_Parity_Rs_240000_330000': 96.0,
  'Power_Parity_Rs_150000_330000': 167.0,
  'Power_Parity_Rs_330000_425000': 84.0,
  'Power_Parity_Rs_425000_545000': 24.0,
  'Power_Parity_Rs_330000_545000': 108.0,
  'Power_Parity_Above_Rs_545000': 32.0,
  'Total_Power_Parity': 1068.0},
 {'_id': ObjectId('66eae254a553d550d3dcebcc'),
  'District_Code': 32,
  'State/UT': 'Himachal Pradesh',
  'District': 'Sirmaur',
  'Population': 529855.0,
  'Male': 276289.0,
  'Female': 253566.0,
  'Literate': 362645.0,
  'Literate_Male': 205617.0,
  'Literate_Female': 157028.0,
  'SC': 160745.0,
  'Male_SC': 83017.0,
  'Female_SC': 77728.0,
  'ST': 11262.0,
  'Male_ST': 5912.0,
  'Female_ST': 5350.0,
  'Workers': 280083.0,
  'Male_Workers': 169399.0,
  'Female_Workers': 110684.0,
  'Main_Workers': 193906.0,
  'Marginal_Workers': 86177.0,
  'Non_Workers': 249772.0,
  'Cultivator_Workers': 182958.0,
  'Agricultural_Workers': 10730.0,
  'Household_Workers': 5313.0,
  'Other_Workers': 81082.0,
  'Hindus': 476830.0,
  'Muslims': 33215.0,
  'Christians': 577.0,
  'Sikhs': 15501.0,
  'Buddhists': 2645.0,
  'Jains': 236.0,
  'Others_Religions': 86.0,
  'Religion_Not_Stated': 765.0,
  'LPG_or_PNG_Households': 28904.0,
  'Housholds_with_Electric_Lighting': 91509.0,
  'Households_with_Internet': 2220.0,
  'Households_with_Computer': 8593.0,
  'Households_Rural': 171102.0,
  'Households_Urban': 21054.0,
  'Households': 192156.0,
  'Below_Primary_Education': 57853.0,
  'Primary_Education': 100123.0,
  'Middle_Education': 78103.0,
  'Secondary_Education': 67080.0,
  'Higher_Education': 38282.0,
  'Graduate_Education': 23352.0,
  'Other_Education': 4048.0,
  'Literate_Education': 368841.0,
  'Illiterate_Education': 140486.0,
  'Total_Education': 509327.0,
  'Young_and_Adult': nan,
  'Middle_Aged': nan,
  'Senior_Citizen': 82471.0,
  'Age_Not_Stated': 301.0,
  'Households_with_Bicycle': 16691.0,
  'Households_with_Car_Jeep_Van': 7459.0,
  'Households_with_Radio_Transistor': 26363.0,
  'Households_with_Scooter_Motorcycle_Moped': 17523.0,
  'Households_with_Telephone_Mobile_Phone_Landline_only': 5229.0,
  'Households_with_Telephone_Mobile_Phone_Mobile_only': 62390.0,
  'Households_with_TV_Computer_Laptop_Telephone_mobile_phone_and_Scooter_Car': 3852.0,
  'Households_with_Television': 58902.0,
  'Households_with_Telephone_Mobile_Phone': 75406.0,
  'Households_with_Telephone_Mobile_Phone_Both': 7787.0,
  'Condition_of_occupied_census_houses_Dilapidated_Households': 2511.0,
  'Households_with_separate_kitchen_Cooking_inside_house': 76236.0,
  'Having_bathing_facility_Total_Households': 74088.0,
  'Having_latrine_facility_within_the_premises_Total_Households': 60246.0,
  'Ownership_Owned_Households': 83947.0,
  'Ownership_Rented_Households': 10156.0,
  'Type_of_bathing_facility_Enclosure_without_roof_Households': 7172.0,
  'Type_of_fuel_used_for_cooking_Any_other_Households': 51.0,
  'Type_of_latrine_facility_Pit_latrine_Households': 2437.0,
  'Type_of_latrine_facility_Other_latrine_Households': 1814.0,
  'Type_of_latrine_facility_Night_soil_disposed_into_open_drain_Households': nan,
  'Type_of_latrine_facility_Flush_pour_flush_latrine_connected_to_other_system_Households': 1245.0,
  'Not_having_bathing_facility_within_the_premises_Total_Households': nan,
  'Not_having_latrine_facility_within_the_premises_Alternative_source_Open_Households': 35731.0,
  'Main_source_of_drinking_water_Un_covered_well_Households': 2064.0,
  'Main_source_of_drinking_water_Handpump_Tubewell_Borewell_Households': 8795.0,
  'Main_source_of_drinking_water_Spring_Households': 1993.0,
  'Main_source_of_drinking_water_River_Canal_Households': 1297.0,
  'Main_source_of_drinking_water_Other_sources_Households': 3558.0,
  'Main_source_of_drinking_water_Other_sources_Spring_River_Canal_Tank_Pond_Lake_Other_sources__Households': 7958.0,
  'Location_of_drinking_water_source_Near_the_premises_Households': 40315.0,
  'Location_of_drinking_water_source_Within_the_premises_Households': 39659.0,
  'Main_source_of_drinking_water_Tank_Pond_Lake_Households': 1110.0,
  'Main_source_of_drinking_water_Tapwater_Households': 75607.0,
  'Main_source_of_drinking_water_Tubewell_Borehole_Households': 1045.0,
  'Household_size_1_person_Households': 4217.0,
  'Household_size_2_persons_Households': 6645.0,
  'Household_size_1_to_2_persons': 10862.0,
  'Household_size_3_persons_Households': 9085.0,
  'Household_size_3_to_5_persons_Households': 47460.0,
  'Household_size_4_persons_Households': 19481.0,

In [38]:
# Fetching back records from Mongodb and storing in DataFrame
import pandas as pd
df=pd.DataFrame(list)

In [39]:
# _id column which is automatically created in mongodb while insertion of records is deleted
del df['_id']

In [40]:
df

,District_Code,State/UT,District,Population,Male,Female,Literate,Literate_Male,Literate_Female,SC,...,Power_Parity_Rs_90000_150000,Power_Parity_Rs_45000_150000,Power_Parity_Rs_150000_240000,Power_Parity_Rs_240000_330000,Power_Parity_Rs_150000_330000,Power_Parity_Rs_330000_425000,Power_Parity_Rs_425000_545000,Power_Parity_Rs_330000_545000,Power_Parity_Above_Rs_545000,Total_Power_Parity
0,10,Jammu and Kashmir,Srinagar,1236829.0,651124.0,585705.0,748584.0,431746.0,316838.0,1068.0,...,668.0,1095.0,319.0,380.0,699.0,240.0,370.0,610.0,445.0,3099.0
1,38,Punjab,Hoshiarpur,1586625.0,809057.0,777568.0,1199699.0,637927.0,561772.0,557504.0,...,925.0,1578.0,586.0,357.0,943.0,360.0,529.0,889.0,730.0,4305.0
2,12,Jammu and Kashmir,Pulwama,560440.0,293064.0,267376.0,293958.0,178326.0,115632.0,402.0,...,119.0,549.0,71.0,96.0,167.0,84.0,24.0,108.0,32.0,1068.0
3,32,Himachal Pradesh,Sirmaur,529855.0,276289.0,253566.0,362645.0,205617.0,157028.0,160745.0,...,209.0,483.0,61.0,44.0,105.0,53.0,87.0,140.0,77.0,930.0
4,47,Punjab,Mansa,769751.0,408732.0,361019.0,423560.0,244037.0,179523.0,258878.0,...,294.0,660.0,236.0,155.0,391.0,202.0,279.0,481.0,56.0,1694.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
635,623,Tamil Nadu,Madurai,3038252.0,1526475.0,1511777.0,2273430.0,1223810.0,1049620.0,408976.0,...,1526.0,3158.0,980.0,502.0,1482.0,372.0,710.0,1082.0,738.0,6917.0
636,622,Tamil Nadu,Sivaganga,1339101.0,668672.0,670429.0,959744.0,526304.0,433440.0,227746.0,...,578.0,1335.0,258.0,205.0,463.0,103.0,137.0,240.0,169.0,2456.0
637,639,Andaman and Nicobar Islands,North AND Middle Andaman,105597.0,54861.0,50736.0,78683.0,43186.0,35497.0,0.0,...,685.0,1895.0,212.0,134.0,346.0,70.0,120.0,190.0,84.0,3151.0
638,631,Tamil Nadu,Krishnagiri,1879809.0,960232.0,919577.0,1187958.0,667062.0,520896.0,267386.0,...,696.0,1851.0,322.0,279.0,601.0,76.0,143.0,219.0,125.0,3203.0
639,636,Pondicherry,Mahe,41816.0,19143.0,22673.0,36470.0,16610.0,19860.0,144.0,...,2316.0,4309.0,1370.0,838.0,2208.0,576.0,978.0,1554.0,1446.0,10027.0

In [41]:
import sqlite3

In [42]:
# installing sqlalchemy to convert DataFrame into Database table
!pip install sqlalchemy

Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.10/dist-packages (2.0.35)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.10/dist-packages (from sqlalchemy) (4.12.2)
Requirement already satisfied: greenlet!=0.4.17 in /usr/local/lib/python3.10/dist-packages (from sqlalchemy) (3.1.1)

In [43]:
# Establishing connection between python and sql
from sqlalchemy import create_engine,text

# Creating a database called census.db in sql
path='sqlite:///census.db'

# connection for database
my_conn=create_engine(path).connect()

In [44]:
# creating a table called 'Census_2011'
df.to_sql(con=my_conn,name='Census_2011',if_exists='replace',index=False)

640

In [45]:
# installing streamlit
!pip install streamlit

Collecting streamlit
  Downloading streamlit-1.39.0-py2.py3-none-any.whl.metadata (8.5 kB)
Requirement already satisfied: altair<6,>=4.0 in /usr/local/lib/python3.10/dist-packages (from streamlit) (4.2.2)
Requirement already satisfied: blinker<2,>=1.0.0 in /usr/lib/python3/dist-packages (from streamlit) (1.4)
Requirement already satisfied: cachetools<6,>=4.0 in /usr/local/lib/python3.10/dist-packages (from streamlit) (5.5.0)
Requirement already satisfied: click<9,>=7.0 in /usr/local/lib/python3.10/dist-packages (from streamlit) (8.1.7)
Requirement already satisfied: numpy<3,>=1.20 in /usr/local/lib/python3.10/dist-packages (from streamlit) (1.26.4)
Requirement already satisfied: packaging<25,>=20 in /usr/local/lib/python3.10/dist-packages (from streamlit) (24.1)
Requirement already satisfied: pandas<3,>=1.4.0 in /usr/local/lib/python3.10/dist-packages (from streamlit) (2.2.2)
Requirement already satisfied: pillow<11,>=7.1.0 in /usr/local/lib/python3.10/dist-packages (from streamlit) (10.4.0)
Requirement already satisfied: protobuf<6,>=3.20 in /usr/local/lib/python3.10/dist-packages (from streamlit) (3.20.3)
Requirement already satisfied: pyarrow>=7.0 in /usr/local/lib/python3.10/dist-packages (from streamlit) (16.1.0)
Requirement already satisfied: requests<3,>=2.27 in /usr/local/lib/python3.10/dist-packages (from streamlit) (2.32.3)
Requirement already satisfied: rich<14,>=10.14.0 in /usr/local/lib/python3.10/dist-packages (from streamlit) (13.9.2)
Requirement already satisfied: tenacity<10,>=8.1.0 in /usr/local/lib/python3.10/dist-packages (from streamlit) (9.0.0)
Requirement already satisfied: toml<2,>=0.10.1 in /usr/local/lib/python3.10/dist-packages (from streamlit) (0.10.2)
Requirement already satisfied: typing-extensions<5,>=4.3.0 in /usr/local/lib/python3.10/dist-packages (from streamlit) (4.12.2)
Requirement already satisfied: gitpython!=3.1.19,<4,>=3.0.7 in /usr/local/lib/python3.10/dist-packages (from streamlit) (3.1.43)
Collecting pydeck<1,>=0.8.0b4 (from streamlit)
  Downloading pydeck-0.9.1-py2.py3-none-any.whl.metadata (4.1 kB)
Requirement already satisfied: tornado<7,>=6.0.3 in /usr/local/lib/python3.10/dist-packages (from streamlit) (6.3.3)
Collecting watchdog<6,>=2.1.5 (from streamlit)
  Downloading watchdog-5.0.3-py3-none-manylinux2014_x86_64.whl.metadata (41 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 41.9/41.9 kB 1.8 MB/s eta 0:00:00
Requirement already satisfied: entrypoints in /usr/local/lib/python3.10/dist-packages (from altair<6,>=4.0->streamlit) (0.4)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.10/dist-packages (from altair<6,>=4.0->streamlit) (3.1.4)
Requirement already satisfied: jsonschema>=3.0 in /usr/local/lib/python3.10/dist-packages (from altair<6,>=4.0->streamlit) (4.23.0)
Requirement already satisfied: toolz in /usr/local/lib/python3.10/dist-packages (from altair<6,>=4.0->streamlit) (0.12.1)
Requirement already satisfied: gitdb<5,>=4.0.1 in /usr/local/lib/python3.10/dist-packages (from gitpython!=3.1.19,<4,>=3.0.7->streamlit) (4.0.11)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.10/dist-packages (from pandas<3,>=1.4.0->streamlit) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas<3,>=1.4.0->streamlit) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.10/dist-packages (from pandas<3,>=1.4.0->streamlit) (2024.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests<3,>=2.27->streamlit) (3.4.0)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests<3,>=2.27->streamlit) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests<3,>=2.27->streamlit) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests<3,>=2.27->streamlit) (2024.8.30)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.10/dist-packages (from rich<14,>=10.14.0->streamlit) (3.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.10/dist-packages (from rich<14,>=10.14.0->streamlit) (2.18.0)
Requirement already satisfied: smmap<6,>=3.0.1 in /usr/local/lib/python3.10/dist-packages (from gitdb<5,>=4.0.1->gitpython!=3.1.19,<4,>=3.0.7->streamlit) (5.0.1)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.10/dist-packages (from jinja2->altair<6,>=4.0->streamlit) (3.0.1)
Requirement already satisfied: attrs>=22.2.0 in /usr/local/lib/python3.10/dist-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (24.2.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.10/dist-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (2024.10.1)
Requirement already satisfied: referencing>=0.28.4 in /usr/local/lib/python3.10/dist-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (0.35.1)
Requirement already satisfied: rpds-py>=0.7.1 in /usr/local/lib/python3.10/dist-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (0.20.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.10/dist-packages (from markdown-it-py>=2.2.0->rich<14,>=10.14.0->streamlit) (0.1.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.2->pandas<3,>=1.4.0->streamlit) (1.16.0)
Downloading streamlit-1.39.0-py2.py3-none-any.whl (8.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.7/8.7 MB 25.2 MB/s eta 0:00:00
Downloading pydeck-0.9.1-py2.py3-none-any.whl (6.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.9/6.9 MB 23.5 MB/s eta 0:00:00
Downloading watchdog-5.0.3-py3-none-manylinux2014_x86_64.whl (79 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 79.3/79.3 kB 4.0 MB/s eta 0:00:00
Installing collected packages: watchdog, pydeck, streamlit
Successfully installed pydeck-0.9.1 streamlit-1.39.0 watchdog-5.0.3

In [46]:
# localtunnel installation
!npm install -g localtunnel

added 22 packages, and audited 23 packages in 2s

3 packages are looking for funding
  run `npm fund` for details

1 moderate severity vulnerability

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.

In [47]:
# To generate password for localtunnel
! wget -q -O - ipv4.icanhazip.com

34.74.174.152

In [48]:
%%writefile app.py
import streamlit as st
import pandas as pd
import sqlite3
from sqlalchemy import create_engine,text
path='sqlite:///census.db'
my_conn=create_engine(path).connect()

st.write(''' The task is to clean, process, and analyze census data from a given source.The goal is to ensure uniformity,
             accuracy, and accessibility of the census data for further analysis and visualization.''')


##1. What is the total population of each district?

df=pd.read_sql(text('select District,Population from Census_2011'), my_conn)
st.write('Total population of each district')
st.write(df)

#2. How many literate males and females are there in each district?

df=pd.read_sql(text('select District,Literate_Male,Literate_Female from Census_2011'), my_conn)
st.write('Literate males and females in each district')
st.write(df)

#3. What is the percentage of workers (both male and female) in each district?

df=pd.read_sql(text('''select District,Workers,Male_Workers,Female_Workers,
(Male_Workers/Workers)*100 as Male_Percent, (Female_Workers/Workers)*100 as Female_Percent
from Census_2011'''), my_conn)
st.write('Percentage of workers (both male and female) in each district')
st.write(df)

#4.How many households have access to LPG or PNG as a cooking fuel in each district?

df=pd.read_sql(text('select District,LPG_or_PNG_Households from Census_2011'), my_conn)
st.write('Households having access to LPG or PNG as a cooking fuel in each district')
st.write(df)

#5. What is the religious composition (Hindus, Muslims, Christians, etc.) of each district?

df=pd.read_sql(text('''select District,(Hindus/Population)*100 as Hindus_Perc,
(Muslims/Population)*100 as Muslims_Perc,
(Christians/Population)*100 as Christians_Perc,
(Sikhs/Population)*100 as Sikhs_Perc,
(Buddhists/Population)*100 as Buddhists_Perc,
(Jains/Population)*100 as Jains_Perc,
(Others_Religions/Population)*100 as Other_Religions_Perc,
(Religion_Not_Stated/Population)*100 as Religion_Not_Stated_Perc from Census_2011'''), my_conn)
st.write('Religious composition in each district')
st.write(df)

#6. How many households have internet access in each district?

df=pd.read_sql(text('select District,Households_with_Internet from Census_2011'), my_conn)
st.write('Households having internet access in each district')
st.write(df)

# 7.What is the educational attainment distribution (below primary, primary, middle, secondary, etc.)
# in each district?

df=pd.read_sql(text('''select District,Below_Primary_Education,Primary_Education,Middle_Education,
Secondary_Education,Higher_Education,Graduate_Education,Other_Education from Census_2011'''), my_conn)
st.write('Educational attainment distribution in each district')
st.write(df)

# 8. How many households have access to various modes of transportation
# (bicycle, car, radio, television, etc.) in each district?

df=pd.read_sql(text('''select District,Households_with_Bicycle,Households_with_Car_Jeep_Van,
Households_with_Scooter_Motorcycle_Moped,
Households_with_TV_Computer_Laptop_Telephone_mobile_phone_and_Scooter_Car from Census_2011'''),my_conn)
st.write('Households having access to various modes of transportation')
st.write(df)

# 9. What is the condition of occupied census houses (dilapidated,
#with separate kitchen, with bathing facility, with latrine facility, etc.) in each district?

df=pd.read_sql(text('''select District,Condition_of_occupied_census_houses_Dilapidated_Households,
Households_with_separate_kitchen_Cooking_inside_house,Having_bathing_facility_Total_Households,
Having_latrine_facility_within_the_premises_Total_Households from Census_2011'''),my_conn)
st.write('Condition of occupied census houses in each district')
st.write(df)

# 10.How is the household size distributed (1 person, 2 persons, 3-5 persons, etc.) in each district?

df=pd.read_sql(text('''select District,Household_size_1_person_Households,
Household_size_2_persons_Households,
Household_size_1_to_2_persons,
Household_size_3_persons_Households,
Household_size_3_to_5_persons_Households,
Household_size_4_persons_Households,
Household_size_5_persons_Households,
Household_size_6_8_persons_Households,
Household_size_9_persons_and_above_Households from Census_2011'''),my_conn)
st.write('Household size distribution in each district')
st.write(df)

# 11.What is the total number of households in each state?

df=pd.read_sql(text('select `State/UT`,sum(Households) from Census_2011 group by `State/UT`'),my_conn)
st.write('Total number of households in each state')
st.write(df)

# 12.How many households have a latrine facility within the premises in each state?

df=pd.read_sql(text('''select `State/UT`,
sum(Having_latrine_facility_within_the_premises_Total_Households)
from Census_2011 group by `State/UT`'''),my_conn)
st.write('Households having latrine facility within the premises in each state')
st.write(df)

# 13.What is the average household size in each state?

df=pd.read_sql(text('select `State/UT`,avg(Households) from Census_2011 group by `State/UT`'),my_conn)
st.write('Average household size in each state')
st.write(df)

# 14. How many households are owned versus rented in each state?

df=pd.read_sql(text('''select `State/UT`,sum(Ownership_Owned_Households),sum(Ownership_Rented_Households)
from Census_2011 group by `State/UT`'''),my_conn)
st.write('Households owned versus rented in each state')
st.write(df)

# 15.What is the distribution of different types of latrine facilities
 #(pit latrine, flush latrine, etc.) in each state?

df=pd.read_sql(text('''select `State/UT`,Type_of_latrine_facility_Pit_latrine_Households,
sum(Type_of_latrine_facility_Other_latrine_Households),
sum(Type_of_latrine_facility_Night_soil_disposed_into_open_drain_Households),
sum(Type_of_latrine_facility_Flush_pour_flush_latrine_connected_to_other_system_Households)
from census_2011 group by `State/UT`'''),my_conn)
st.write('Distribution of different types of latrine facilities in each state')
st.write(df)

# 16.How many households have access to drinking water sources near the premises in each state?

df=pd.read_sql(text('''select `State/UT`,sum(Location_of_drinking_water_source_Near_the_premises_Households)
 from Census_2011 group by `State/UT`'''),my_conn)
st.write('Households having access to drinking water sources near the premises in each state')
st.write(df)

# 17.What is the average household income distribution in each state based on the power parity categories?

df=pd.read_sql(text('''select `State/UT`,
avg(Power_Parity_Less_than_Rs_45000),
avg(Power_Parity_Rs_45000_90000),
avg(Power_Parity_Rs_90000_150000),
avg(Power_Parity_Rs_45000_150000),
avg(Power_Parity_Rs_150000_240000),
avg(Power_Parity_Rs_240000_330000),
avg(Power_Parity_Rs_150000_330000),
avg(Power_Parity_Rs_330000_425000),
avg(Power_Parity_Rs_425000_545000),
avg(Power_Parity_Rs_330000_545000),
avg(Power_Parity_Above_Rs_545000) from Census_2011 group by `State/UT`'''),my_conn)
st.write('Average household income distribution in each state based on the power parity categories')
st.write(df)

# 18. What is the percentage of married couples with different household sizes in each state?

df=pd.read_sql(text('''select `State/UT`,
sum((Married_couples_1_Households/(Married_couples_1_Households+Married_couples_2_Households+
Married_couples_3_or_more_Households+Married_couples_None_Households))*100),
sum((Married_couples_2_Households/(Married_couples_1_Households+Married_couples_2_Households+
Married_couples_3_or_more_Households+Married_couples_None_Households))*100),
sum((Married_couples_3_or_more_Households/(Married_couples_1_Households+Married_couples_2_Households+
Married_couples_3_or_more_Households+Married_couples_None_Households))*100),
sum((Married_couples_None_Households/(Married_couples_1_Households+Married_couples_2_Households+
Married_couples_3_or_more_Households+Married_couples_None_Households))*100) from Census_2011 group by `State/UT`'''),my_conn)
st.write('percentage of married couples with different household sizes in each state')
st.write(df)

# 19. How many households fall below the poverty line in each state based on the power parity categories?

df=pd.read_sql(text('select `State/UT`,sum(Power_Parity_Less_than_Rs_45000) from census_2011 group by `State/UT`'),my_conn)
st.write('Households below the poverty line in each state based on the power parity categories')
st.write(df)

# 20. What is the overall literacy rate (percentage of literate population) in each state?

df=pd.read_sql(text('select `State/UT`,sum((Literate/Population)*100) from Census_2011 group by `State/UT`'),my_conn)
st.write('Overall literacy rate in each state')
st.write(df)

Writing app.py

In [ ]:
# A url is generated for viewing streamlit in browser
! streamlit run app.py & npx localtunnel --port 8501

Collecting usage statistics. To deactivate, set browser.gatherUsageStats to false.

your url is: https://sad-poets-attend.loca.lt

  You can now view your Streamlit app in your browser.

  Local URL: http://localhost:8501
  Network URL: http://172.28.0.12:8501
  External URL: http://34.74.174.152:8501